name: Docker Image CI

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build image
        run: docker build . -t ghcr.io/riley-momo/conda-process-mining:latest

      - name: Push image
        run: docker push ghcr.io/riley-momo/conda-process-mining:latest